defaults {
    no_path_retry 10
    find_multipaths yes
    user_friendly_names yes
}
devices {
    device {
        vendor                  "HITACHI"
        product                 "OPEN-.*"
        path_grouping_policy    multibus
        path_checker            tur
        hardware_handler        "0"
        path_selector           "round-robin 0"
        failback                immediate
        rr_weight               priorities
    }
}
